incomplete attempt to update to glfw 3.3
The previous versions of glfw no longer built on Mac. The newest version
of glfw is not backwards compatible; see
https://www.glfw.org/docs/3.0/moving.htm for all the details, but there
are many renamed functions and some removed ones (such as
`glfwSetMouseWheel`). Additionally, everything related to threads is
gone, so we import tinycthread instead.

I was able to fix all of the build errors in the SVS code, but the build
of glfw fails with many, many errors:

Core/SVS/glfw/src/glx_context.c:43:33: error: unknown type name 'GLXFBConfig'
static int getGLXFBConfigAttrib(GLXFBConfig fbconfig, int attrib)
                                ^
Core/SVS/glfw/src/glx_context.c:46:5: error: implicit declaration of function 'glXGetFBConfigAttrib' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    glXGetFBConfigAttrib(_glfw.x11.display, fbconfig, attrib, &value);
    ^
Core/SVS/glfw/src/glx_context.c:46:5: note: did you mean 'getGLXFBConfigAttrib'?
Core/SVS/glfw/src/glx_context.c:43:12: note: 'getGLXFBConfigAttrib' declared here
static int getGLXFBConfigAttrib(GLXFBConfig fbconfig, int attrib)
           ^
Core/SVS/glfw/src/glx_context.c:46:32: error: no member named 'x11' in 'struct _GLFWlibrary'
    glXGetFBConfigAttrib(_glfw.x11.display, fbconfig, attrib, &value);
                         ~~~~~ ^
Core/SVS/glfw/src/glx_context.c:53:35: error: unknown type name 'GLXFBConfig'
                                  GLXFBConfig* result)
                                  ^
Core/SVS/glfw/src/glx_context.c:55:5: error: use of undeclared identifier 'GLXFBConfig'
    GLXFBConfig* nativeConfigs;
    ^
Core/SVS/glfw/src/glx_context.c:55:18: error: use of undeclared identifier 'nativeConfigs'
    GLXFBConfig* nativeConfigs;
                 ^
...

I likely haven't imported the project correctly; the correct way to
compile it into a project is documented here:
https://www.glfw.org/docs/latest/build_guide.html#build_link_pkgconfig.
It involves first configuring with CMake, then using package-config to
get all of the compiler flags. This could be done on a GitHub action
runner, as CMake is installed, though we would also have to update our
build requirements/documentation. I don't know if this is possible on
Windows, though, so I don't want to pursue this right now.

Related: #411.