Ignore __stdcall on non-Win32 platforms
The __stdcall calling convention was only used on 32-bit Windows, and
does nothing on other platforms. It's safe to simply ignore it.
See https://stackoverflow.com/a/46537073/474819.

This is an attempt to fix the errors below:

build/Core/ClientSMLSWIG/CSharp/CSharpCallbackByHand.h:963:24: error: expected ‘)’ before ‘*’ token
  963 | typedef void (__stdcall* AgentEventCallback)(int eventID, CallbackDataPtr callbackData, kernelPtr jKernel, char* agentName) ;
      |              ~         ^
      |                        )
build/Core/ClientSMLSWIG/CSharp/CSharpCallbackByHand.h: In function ‘void AgentEventHandler(sml::smlAgentEventId, void*, sml::Agent*)’:
build/Core/ClientSMLSWIG/CSharp/CSharpCallbackByHand.h:972:5: error: ‘AgentEventCallback’ was not declared in this scope
  972 |     AgentEventCallback callback = (AgentEventCallback)pData->m_CallbackFunction ;
      |     ^~~~~~~~~~~~~~~~~~
build/Core/ClientSMLSWIG/CSharp/CSharpCallbackByHand.h:978:5: error: ‘callback’ was not declared in this scope; did you mean ‘calloc’?
  978 |     callback(pData->m_EventID, pData->m_CallbackData, pData->m_Kernel, csharpAgentName) ;
      |     ^~~~~~~~
      |     calloc