Pin wheel version to fix build errors
Based on this person's report: https://saxonica.plan.io/issues/6509 and on the
changelog's statement that bdist_wheel was deprecated in 0.44.0:
https://wheel.readthedocs.io/en/stable/news.html.

Fixes this error in CI while building wheels:

 scons: *** [build/wheel/soar_sml-9.6.4.202409272142.dev24.dist-info/WHEEL] ImportError : cannot import name 'get_platform' from 'wheel.bdist_wheel' (/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py)
    Traceback (most recent call last):
      File "/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/SCons/Action.py", line 1318, in execute
        result = self.execfunction(target=target, source=rsources, env=env)
      File "/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/enscons/__init__.py", line 491, in wheelmeta_builder
        % (str(env["ROOT_IS_PURELIB"]).lower(), get_tag(env))
      File "/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/enscons/__init__.py", line 429, in get_tag
        from wheel.bdist_wheel import get_platform, tags, get_abi_tag
    ImportError: cannot import name 'get_platform' from 'wheel.bdist_wheel' (/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py)
    scons: building terminated because of errors.
    Traceback (most recent call last):
      File "/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/enscons/api.py", line 34, in _run
        SCons.Script.Main.main()
      File "/tmp/pip-build-env-u8eb8a27/overlay/lib/python3.9/site-packages/SCons/Script/Main.py", line 1462, in main
        sys.exit(exit_status)
    SystemExit: 2