Add missing include
Fixes this build error on Linix:

memory_manager.h:134:58: error: ‘string’ in namespace ‘std’ does not
name a type
134 | bool add_block_to_memory_pool_by_name(const std::string& pool_name
    |                                                  ^~~~~~