std::unary_function is removed in C++17
For some reason, MSVC is the only compiler that gives an error for it,
though.

Attempting to fix this error:

error C2504: 'unary_function': base class undefined