Fix slash in path name
`\*` was being interpreted as an escape; Windows can also accept `/`,
and it's used on other systems (which are now supported by CSharp!),
so switch to it.

Fixes the following error:

error CS2001: Source file '/home/runner/work/Soar/Soar/build/Core/ClientSMLSWIG/CSharp/src*.cs' could not be found.