Don't override intrinsic function log2
log2 was added in MSVC 2013; see release notes here:
https://devblogs.microsoft.com/cppblog/c99-library-support-in-visual-studio-2013/

Fixes the following error:

Core\SVS\src\windows\platform_specific.h(23): error C2169: 'log2': intrinsic function, cannot be defined