cast pointers to uintptr_t, not unsigned int
Integer arithmetic with pointer-sized data can safely be done on
`uintptr_t`; `int` is only 32 bits, though, so it can't store a
(potentially) 64-bit pointer.

This should fix two errors in the compilation of the C# SML code:

    build/Core/ClientSMLSWIG/CSharp/CSharpCallbackByHand.h:292:75: error: cast from pointer to smaller type 'unsigned int' loses information
        unsigned int csharpOutputWME = SWIG_csharp_allocateWMElement_callback((unsigned int)pOutputWME) ;