upgrade to SCons 4.4.0
Replace the contents of the scons/ directory with a copy of scons-local
downloaded from
http://prdownloads.sourceforge.net/scons/scons-local-4.4.0.tar.gz.

This contains the configurations needed for compiling on Windows with
the 2022 tool releases.

Fixes the following and related errors on the Windows build:

In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/corecrt_wstdio.h:13,
                 from C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/stdio.h:13,
                 from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include/cstdio:12,
                 from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include/iosfwd:12,
                 from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include/xstring:13,
                 from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include/string:11,
                 from Core\shared\assert.hpp:13,
                 from Core\shared\assert.cpp:9:
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt/corecrt_stdio_config.h:35:10: error: #error Unsupported architecture
   35 |         #error Unsupported architecture
      |          ^~~~~